---
abstract: 'RT-Extension-TravisCI Extension'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: '6.36'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RT-Extension-TravisCI
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
